This is makeindex, version 2.15 [TeX Live 2018] (kpathsea + Thai support).
Scanning style file /Users/jonathanbabyn/Documents/GitHub/SSM3PS/analysis/.texpadtmp/spamReport.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file /Users/jonathanbabyn/Documents/GitHub/SSM3PS/analysis/.texpadtmp/spamReport.acn....done (136 entries accepted, 0 rejected).
Sorting entries....done (1045 comparisons).
Generating output file /Users/jonathanbabyn/Documents/GitHub/SSM3PS/analysis/.texpadtmp/spamReport.acr....done (74 lines written, 0 warnings).
Output written in /Users/jonathanbabyn/Documents/GitHub/SSM3PS/analysis/.texpadtmp/spamReport.acr.
Transcript written in /Users/jonathanbabyn/Documents/GitHub/SSM3PS/analysis/.texpadtmp/spamReport.alg.
