// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// catchProp
Eigen::VectorXd catchProp(Eigen::Map<Eigen::VectorXd > catchy);
RcppExport SEXP _SSM3PS_catchProp(SEXP catchySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::VectorXd > >::type catchy(catchySEXP);
    rcpp_result_gen = Rcpp::wrap(catchProp(catchy));
    return rcpp_result_gen;
END_RCPP
}
// makeCRLs
Eigen::MatrixXd makeCRLs(Eigen::Map<Eigen::MatrixXd> cProps);
RcppExport SEXP _SSM3PS_makeCRLs(SEXP cPropsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::Map<Eigen::MatrixXd> >::type cProps(cPropsSEXP);
    rcpp_result_gen = Rcpp::wrap(makeCRLs(cProps));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SSM3PS_catchProp", (DL_FUNC) &_SSM3PS_catchProp, 1},
    {"_SSM3PS_makeCRLs", (DL_FUNC) &_SSM3PS_makeCRLs, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_SSM3PS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
