# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' catchProp
#'
#' make a row prop
#'
#' Why doesn't this work
#'
#' @param catchy a row to proportionize
#' @export
catchProp <- function(catchy) {
    .Call('_SSM3PS_catchProp', PACKAGE = 'SSM3PS', catchy)
}

#'makeCRLs
#'
#' Turn matrix of proportions into CRLs
#'
#' @param cProps matrix of proportions
#' @export
makeCRLs <- function(cProps) {
    .Call('_SSM3PS_makeCRLs', PACKAGE = 'SSM3PS', cProps)
}

